sudo: required
language: generic
services:
- docker
deploy:
  provider: gae
  project: verdant-medley-276408
  keyfile: verdant-medley-276408-5a76c40aadc3.json
  verbosity: debug
  skip_cleanup: true
  default: true
  on:
    branch: master
