sudo: required
language: generic
services:
- docker
before-install:
- docker build -t reactapp -f Dockerfile.dev .
script:
- docker run -e CI=true reactapp npm run test
deploy:
  provider: gae
  skip_cleanup: true
  keyfile: verdant-medley-276408-4833bc1d928a.json
  project: verdant-medley-276408
  default: true
  on:
    branch: master
before_install:
- openssl aes-256-cbc -K $encrypted_d80a2d296111_key -iv $encrypted_d80a2d296111_iv -in credentials.tar.gz.enc -out credentials.tar.gz -d
