sudo: required
language: generic
services:
  - docker
before-install:
  - docker build -t reactapp -f Dockerfile.dev .
script:
  - docker run -e CI=true reactapp npm run test

deploy:
    provider: gae
    # Skip cleanup so api_key.py and vendored dependencies are still there
    skip_cleanup: true
    keyfile: verdant-medley-276408-5a76c40aadc3.json
    project: verdant-medley-276408
    default: true
    on:
      branch: master

