sudo: required
language: generic
services:
- docker
before-install:
- docker build -t reactapp -f Dockerfile.dev .
script:
- docker run -e CI=true reactapp npm run test
deploy:
  provider: gae
  skip_cleanup: true
  keyfile: verdant-medley-276408-4833bc1d928a.json
  project: verdant-medley-276408
  default: true
  on:
    branch: master
